# Generated by Django 6.0.7 on 2026-07-26 05:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='LicenceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Licence Category',
                'verbose_name_plural': 'Licence Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shop_name', models.CharField(max_length=200)),
                ('whatsapp_number', models.CharField(help_text='Used for OTP login and WhatsApp notifications.', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?91?\\d{10}$', 'Enter a valid Indian WhatsApp number.')])),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['shop_name'],
            },
        ),
        migrations.CreateModel(
            name='LicenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licence_types', to='licenses.licencecategory')),
            ],
            options={
                'verbose_name': 'Licence Type',
                'verbose_name_plural': 'Licence Types',
                'ordering': ['name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_number', models.CharField(max_length=100, unique=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRING_SOON', 'Expiring Soon'), ('EXPIRED', 'Expired'), ('RENEWED', 'Renewed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licences', to='licenses.dealer')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licences', to='licenses.financialyear')),
                ('licence_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licences', to='licenses.licencetype')),
            ],
            options={
                'verbose_name': 'Licence',
                'verbose_name_plural': 'Licences',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('PUSH', 'Push Notification'), ('WHATSAPP', 'WhatsApp')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('message_content', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='licenses.dealer')),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='licenses.licence')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('dealer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to='licenses.dealer')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='ReminderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_expiry', models.PositiveIntegerField()),
                ('scheduled_date', models.DateField()),
                ('is_sent', models.BooleanField(default=False)),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='licenses.licence')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='licenses.state')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Taluka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talukas', to='licenses.district')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dealer',
            name='taluka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dealers', to='licenses.taluka'),
        ),
        migrations.AddIndex(
            model_name='licence',
            index=models.Index(fields=['expiry_date'], name='licenses_li_expiry__633282_idx'),
        ),
        migrations.AddIndex(
            model_name='licence',
            index=models.Index(fields=['status'], name='licenses_li_status_f5f774_idx'),
        ),
        migrations.AddIndex(
            model_name='licence',
            index=models.Index(fields=['dealer'], name='licenses_li_dealer__49f87b_idx'),
        ),
        migrations.AddIndex(
            model_name='licence',
            index=models.Index(fields=['financial_year'], name='licenses_li_financi_b74ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='licence',
            index=models.Index(fields=['licence_type'], name='licenses_li_licence_527a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['channel'], name='licenses_no_channel_cdd92b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status'], name='licenses_no_status_399601_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['sent_at'], name='licenses_no_sent_at_cbe360_idx'),
        ),
        migrations.AddIndex(
            model_name='reminderschedule',
            index=models.Index(fields=['scheduled_date'], name='licenses_re_schedul_73fc7d_idx'),
        ),
        migrations.AddIndex(
            model_name='reminderschedule',
            index=models.Index(fields=['is_sent'], name='licenses_re_is_sent_6cb282_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('state', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='taluka',
            unique_together={('district', 'name')},
        ),
    ]
