# Generated by Django 6.0.7 on 2026-07-31 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='whatsapp_number',
            field=models.CharField(help_text='Used for OTP login and WhatsApp notifications.', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^(\\+91|91)?\\d{10}$', 'Enter a valid Indian WhatsApp number.')]),
        ),
    ]
