# Generated by Django 6.0.7 on 2026-08-05 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_alter_dealer_whatsapp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(max_length=200)),
                ('product_detail', models.CharField(blank=True, max_length=200, null=True)),
                ('valid_upto', models.DateField()),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='licenses.licence')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
