# Generated by Django 6.0.7 on 2026-08-05 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_licenceentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='licenceentry',
            name='product_detail',
        ),
        migrations.AddField(
            model_name='licenceentry',
            name='fertilizer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_entries', to='licenses.fertilizertype'),
        ),
    ]
