# Generated by Django 6.0.7 on 2026-08-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0005_fertilizertype_remove_licenceentry_product_detail_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='licence',
            name='licenses_li_financi_b74ce3_idx',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='financial_year',
        ),
        migrations.DeleteModel(
            name='FinancialYear',
        ),
    ]
