# Generated by Django 6.0.7 on 2026-08-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0006_remove_licence_licenses_li_financi_b74ce3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenceentry',
            name='fertilizer_type',
        ),
        migrations.AddField(
            model_name='licenceentry',
            name='fertilizer_type',
            field=models.ManyToManyField(blank=True, related_name='licence_entries', to='licenses.fertilizertype'),
        ),
    ]
