# Generated by Django 6.0.7 on 2026-08-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0007_remove_licenceentry_fertilizer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('STUBBED', 'Stubbed (not actually sent)')], default='PENDING', max_length=10),
        ),
    ]
