# Generated by Django 6.0.7 on 2026-08-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0008_alter_notificationlog_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='licence',
            constraint=models.UniqueConstraint(fields=('dealer', 'licence_type'), name='unique_licence_per_dealer_and_type'),
        ),
    ]
