# Generated by Django 6.0.7 on 2026-08-08 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0009_licence_unique_licence_per_dealer_and_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderschedule',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='licenses.licenceentry'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
