# Generated by Django 6.0.7 on 2026-08-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0010_reminderschedule_entry_alter_licence_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='is_expiry_day',
            field=models.BooleanField(default=False),
        ),
    ]
