# Generated by Django 6.0.7 on 2026-08-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0011_notificationlog_is_expiry_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
